### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by raulogh** [keksexception/LobbyNPCs#11]
**Describe the bug**

**To Reproduce**
1. Casually creating the npc
2. Completly doing every steps of creating
3. I get to the "Sneak when player sneak?"
4. Press yes => ERROR, Press no => ERROR

**Expected behavior**

to not give any error i guess?

**Console log**
If applicable, add the console log with the error to help explain your problem.

[15:20:55 INFO]: HyperGDD issued server command: /pluginlibchoice yes
[15:20:55 ERROR]: Could not pass event PlayerCommandPreprocessEvent to PluginLib v1.1-b5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[server.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1107) [server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Spigot-c3c767f-33d5de3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_202]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [server.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NoClassDefFoundError: com/google/gson/JsonElement
        at de.raffi.lobbynpcs.commands.LobbyNPCCommand$1$1$1$1$1$1$1$1$1$1.onHandlerRemoved(LobbyNPCCommand.java:106) ~[?:?]
        at de.raffi.pluginlib.test.InputHandler.onCommand(InputHandler.java:53) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[server.jar:git-Spigot-c3c767f-33d5de3]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_202]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
        at de.raffi.lobbynpcs.commands.LobbyNPCCommand$1$1$1$1$1$1$1$1$1$1.onHandlerRemoved(LobbyNPCCommand.java:106) ~[?:?]
        at de.raffi.pluginlib.test.InputHandler.onCommand(InputHandler.java:53) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[server.jar:git-Spigot-c3c767f-33d5de3]
        ... 15 more

**Please complete the following information or send the information displayed by typing /lobbynpc info:**
 - Pluginversion : versionid:4 versionname:1.2-r7
 - PluginLib version : versionid:4 versionname:1.1-b5
 - Server version: NMS - v1_8_R1 | Bukkit - 1.8-R0.1-SNAPSHOT | Server Version: git-Spigot-c3c767f-33d5de3 (MC: 1.8)
 - Java version: Unable to get this through command : "An internal error occured while attemping to perform this command" but the version of java i use is:  jre1.8.0_202

**Installed plugins**
A list of all plugins installed on the server.

LobbyNPCs V1.2-r7.jar
PluginLib1.1-b5.jar

**Additional context**
nothing..

**Comment by keksexception** [comment]
Hey, thanks for you patience. You are using a very old Serverversion that is not supported by PluginLib yet. I will post an update within the next hour, that will add support for your server-version

**Comment by keksexception** [comment]
Bad news. It may a take a while until this problem is solved. Minecraft 1.8 Handles packets a lot different than 1.8.8 and higher does. The current plugin is not able to compensate that many changes in the servercode. If it is possible for you, i would recomming upgrading to spigot 1.8.8 or higher due to a more stable and more supported serversystem.

**Comment by keksexception** [comment]
I found another problem with the Serverversion. Spigot 1.8 does not provide com.google.gson.JsonElement which is essential for
the LabyModAPI and handling plugin data. I cannot fix that, because it is a problem with that 1.8 spigot itself and the thirdparty plugin LabyModAPI .
