### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jachimoo** [keksexception/LobbyNPCs#4]
**Describe the bug**
Plugin don't work
I install pluginLib and the plugin in lastest version.

**To Reproduce**
1. Have 1.15.2 minecraft paper server
2. 
3. 
4. 

**Expected behavior**

**Console log**
[11:42:30 INFO]: [LobbyNPCs] Enabling LobbyNPCs v1.1-r1*
[11:42:30 WARN]: [LobbyNPCs] Loaded class de.raffi.pluginlib.test.YesNoCallback from PluginLib v1.1-b3 which is not a depend, softdepend or loadbefore of this plugin.
[11:42:30 ERROR]: Error occurred while enabling LobbyNPCs v1.1-r1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Listener
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.15.2.jar:git-Paper-282]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:215) ~[patched_1.15.2.jar:git-Paper-282]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.15.2.jar:git-Paper-282]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-282]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at de.raffi.lobbynpcs.main.LobbyNPCs.onEnable(LobbyNPCs.java:52) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-282]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-282]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-282]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-282]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-282]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-282]        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-282]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:897) ~[patched_1.15.2.jar:git-Paper-282]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.plugin.Listener
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-282]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-282]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        ... 19 more

**Please complete the following information or send the information displayed by typing /lobbynpc info:**
 - Pluginversion 1.1-r1
 - PluginLib version v1.1-b3
 - Server version 1.15.2
 - Java version 8

**Installed plugins**
DeluxeHub
EasyPrefix
EssentialsX
LoginSecurity
LuckPerms
PlaceholderApi
PluginConstructorApi
ViaVersions
Worldedit
worldguard
WorldeditselectionVisualizer

**Additional context**
If PluginLib and LobbyNPC's are installed in plugin folder no one can join server

**Comment by keksexception** [comment]
I trying to get it fixed as soon as possible 😁

**Comment by Jachimoo** [comment]
and If i want to join to the server it says
[Proxy] lost connection to the server.
when I uninstall both plugins server works properly.
I was using Java edition of minecraft

**Comment by Jachimoo** [comment]
[12:37:20 INFO]: Kaiser lost connection: Internal Exception: java.lang.IllegalStateException: PacketSendEvent may only be triggered synchronously.

log when I try to join

**Comment by keksexception** [comment]
Hey,
i have good and bad news.

The good news is, that **i got your bug fixed**. I will upload the update today on spigotmc. You then have to update Lobby NPCs and PluginLib.

The bad news is, that you can't use the **/lobbynpc remove** inventory in **1.14 and 1.15**. If you want to remove an npc you have to stop your server, delete npcdata.dat in the LobbyNPCs folder and start it again.

**Comment by keksexception** [comment]
Bug fixed are now online on spigotmc: [Click here to open spigot page](https://www.spigotmc.org/resources/%E2%9A%A1lobby-npcs%E2%9A%A1-1-8-1-10-1-11-1-12-1-14-1-15-must-have.79022/)
