### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by virtualWinter** [keksexception/LobbyNPCs#9]
**Describe the bug**

**To Reproduce**
1. Just placed the plugin in the plugins folder

**Expected behavior**

Idk, to work?

**Console log**

[19:32:00 ERROR]: Could not load 'plugins/LobbyNPCs.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: de/raffi/pluginlib/utils/UpdateCallback
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:190) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.NoClassDefFoundError: de/raffi/pluginlib/utils/UpdateCallback
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: de.raffi.pluginlib.utils.UpdateCallback
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-PaperSpigot-"d6c3d19"]
        ... 6 more

**Please complete the following information or send the information displayed by typing /lobbynpc info:**
 - Pluginversion Latest
 - PluginLib version Latest
 - Server version 1.8.8 Paper
 - Java version Java 8

**Installed plugins**
A list of all plugins installed on the server.
Plugins (9): AquaCore, LabyModAPI, FastAsyncWorldEdit, ViaVersion, Vault, ProtocolLib, ViaRewind, WorldEdit, PluginLib

**Additional context**

**Comment by keksexception** [comment]
Hey, thanks for your Bug-report! I do now work on it.

**Comment by keksexception** [comment]
Good news. I was able to reproduce the error and was to fix it. 

What caused the error?
The plugin tried to load a class in PluginLib that did not exist in the latest public available PluginLib version.

How to fix the issue:
Download newest version of LobbyNPCs and more important PluginLib.

Please let me know if this worked for you !

**Comment by virtualWinter** [comment]
It worked! Also thanks for the fast response.

*Edit*

Console log:
[22:37:42 INFO]: vWinter issued server command: /pluginlibchoice yes
[22:40:16 INFO]: vWinter issued server command: /lobbynpc
[22:40:20 INFO]: vWinter issued server command: /lobbynpc help
[22:40:30 INFO]: vWinter issued server command: /lobbynpc create
[22:40:37 INFO]: vWinter issued server command: /pluginlibchoice yes
[22:40:54 INFO]: vWinter issued server command: /pluginlibchoice yes
[22:41:07 INFO]: vWinter issued server command: /pluginlibchoice no
[22:41:37 INFO]: vWinter issued server command: /pluginlibchoice yes
[22:41:42 INFO]: vWinter issued server command: /pluginlibchoice no
[22:41:45 INFO]: vWinter issued server command: /pluginlibchoice no
[22:41:48 INFO]: vWinter issued server command: /pluginlibchoice no
[22:41:48 WARN]: java.lang.NullPointerException
[22:41:48 WARN]:        at de.raffi.pluginlib.utils.UUIDFetcher.getUUIDAt(UUIDFetcher.java:88)
[22:41:48 WARN]:        at de.raffi.pluginlib.utils.UUIDFetcher.getUUID(UUIDFetcher.java:54)
[22:41:48 WARN]:        at de.raffi.pluginlib.npc.NPC.<init>(NPC.java:56)
[22:41:48 WARN]:        at de.raffi.lobbynpcs.commands.LobbyNPCCommand.createNPC(LobbyNPCCommand.java:324)
[22:41:48 WARN]:        at de.raffi.lobbynpcs.commands.LobbyNPCCommand$1$1$1$1$1$1$1$1$1$1.onHandlerRemoved(LobbyNPCCommand.java:128)
[22:41:48 WARN]:        at de.raffi.pluginlib.test.InputHandler.onCommand(InputHandler.java:53)
[22:41:48 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:41:48 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:41:48 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:41:48 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[22:41:48 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[22:41:48 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[22:41:48 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:41:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[22:41:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1181)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[22:41:48 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:41:48 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:741)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:680)
[22:41:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:583)
[22:41:48 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:41:49 ERROR]: java.lang.NullPointerException
[22:41:49 INFO]: vWinter lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer

**Comment by keksexception** [comment]
Hey, unfortuneatly i was not able to reproduce this error yet. I need more information.

- Which name you gave the NPC
- From which player you tried to load the skin
- Did the NPC spawn, after the error occured

Thanks!

**Comment by virtualWinter** [comment]
Npc name: &bPractice
The player i tried to load skin: vWinter
No it didnt.

**Comment by keksexception** [comment]
Hey, i was able to identify the error. 
Why does it happen?
When you click on [Yes] by "Fetch the UUID of ..." The plugin requests the UUID of the Player you entered befor. After that it spawns a player with exactly that UUID. But because you entered your name, the plugin tries to spawn a player that already exist (you). Minecraft does not allow to spawn the same player twice. You can avoid that problem by clicking on [No] when you are asked if you want to fetch the UUID. This should not influence how the NPC looks.

**Comment by virtualWinter** [comment]
I did that but the npc is missing the second skin layer

**Comment by keksexception** [comment]
Unfortunatly the plugin is not able to show the second skin layer at the moment

**Comment by virtualWinter** [comment]
Well thanks for the fast support <3

**Comment by keksexception** [comment]
I thank you for your using my plugin and reporting the bugs!
